
package com.prchny.base.entity;

// Generated Oct 4, 2010 3:37:56 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmailDomain generated by hbm2java
 */
@Entity
@Table(name = "email_domain", uniqueConstraints = @UniqueConstraint(columnNames = "domain"))
public class EmailDomain implements java.io.Serializable {
  
  /**
   * 
   */
  private static final long serialVersionUID = -5115417299058460518L;
  
  private Integer id;
  
  private String domain;
  
  private boolean blocked;
  
  private String pattern;
  
  public EmailDomain() {
  
  }
  
  public EmailDomain(final String domain, final boolean blocked) {
  
    this.domain = domain;
    this.blocked = blocked;
    pattern = null;
  }
  
  public EmailDomain(final String domain, final boolean blocked,
      final String pattern) {
  
    this.domain = domain;
    this.blocked = blocked;
    this.pattern = pattern;
  }
  
  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
  
    return id;
  }
  
  public void setId(final Integer id) {
  
    this.id = id;
  }
  
  @Column(name = "domain", unique = true, nullable = false, length = 100)
  public String getDomain() {
  
    return domain;
  }
  
  public void setDomain(final String domain) {
  
    this.domain = domain;
  }
  
  @Column(name = "blocked", nullable = false)
  public boolean isBlocked() {
  
    return blocked;
  }
  
  public void setBlocked(final boolean blocked) {
  
    this.blocked = blocked;
  }
  
  @Column(name = "pattern")
  public String getAddressPattern() {
  
    return pattern;
  }
  
  public void setAddressPattern(final String pattern) {
  
    this.pattern = pattern;
  }
}
