
package com.prchny.base.entity;

// Generated Aug 20, 2010 8:23:32 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SmsChannel generated by hbm2java
 */
@Entity
@Table(name = "sms_channel", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SmsChannel implements java.io.Serializable {
  
  /**
   * 
   */
  private static final long serialVersionUID = -9062992739681479728L;
  
  private Integer id;
  
  private String name;
  
  private String senderClassName;
  
  private String username;
  
  private String password;
  
  private String mask;
  
  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
  
    return id;
  }
  
  public void setId(final Integer id) {
  
    this.id = id;
  }
  
  @Column(name = "name", unique = true, nullable = false, length = 48)
  public String getName() {
  
    return name;
  }
  
  public void setName(final String name) {
  
    this.name = name;
  }
  
  @Column(name = "sender_class", nullable = false, length = 200)
  public String getSenderClassName() {
  
    return senderClassName;
  }
  
  public void setSenderClassName(final String senderClassName) {
  
    this.senderClassName = senderClassName;
  }
  
  /**
   * @return the username
   */
  @Column(name = "username", nullable = true, length = 48)
  public String getUsername() {
  
    return username;
  }
  
  /**
   * @param username
   *          the username to set
   */
  public void setUsername(final String username) {
  
    this.username = username;
  }
  
  /**
   * @return the password
   */
  @Column(name = "password", nullable = true, length = 48)
  public String getPassword() {
  
    return password;
  }
  
  /**
   * @param password
   *          the password to set
   */
  public void setPassword(final String password) {
  
    this.password = password;
  }
  
  @Column(name = "mask", nullable = true, length = 32)
  public String getMask() {
  
    return mask;
  }
  
  public void setMask(final String mask) {
  
    this.mask = mask;
  }
  
}
